# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7e8e10aef0bb2701be8c9d7cd5ab7e7dc346ec16f60346c6775902eed22be32cac95cacd800442ef1282ce0c53653f3e7561c5811c4fe57faf8d9586b2ea52

test:
  secret_key_base: 287c4acf5ba32707e2cca538730833deb965235936d1756e779c54e5b3a26a6d9d9f367d9940cf000bbe33327432baf0b4bb892997fbebc249a093f5a32f7344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
